;;; Directory Local Variables         -*- no-byte-compile: t; -*-
;;; For more information see (info "(emacs) Directory Variables")
((clojure-dart-ts-mode . ((apheleia-formatter . (zprint))))
 (clojure-jank-ts-mode . ((apheleia-formatter . (zprint))))
 (clojure-mode . ((apheleia-formatter . (zprint))))
 (clojure-ts-mode . ((apheleia-formatter . (zprint))))
 (clojurec-mode . ((apheleia-formatter . (zprint))))
 (clojurec-ts-mode . ((apheleia-formatter . (zprint))))
 (clojurescript-mode . ((apheleia-formatter . (zprint))))
 (clojurescript-ts-mode . ((apheleia-formatter . (zprint)))))
